miascakehouse/models.py
from . import db

class Category(db.Model):
    __tablename__='categories'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False, default = 'Pink_rosette.webp')
    cakes = db.relationship('Cake', backref='Category', cascade="all, delete-orphan")

    def __repr__(self):
        str = "Id: {}, Name: {}, Description: {}, Image: {}\n" 
        str =str.format( self.id, self.name,self.description,self.image)
        return str

orderdetails = db.Table('orderdetails', 
    db.Column('order_id', db.Integer,db.ForeignKey('orders.id'), nullable=False),
    db.Column('cake_id',db.Integer,db.ForeignKey('cakes.id'),nullable=False),
    db.PrimaryKeyConstraint('order_id', 'cake_id') )

class Cake(db.Model):
    __tablename__='cakes'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64),nullable=False)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False)
    size = db.Column(db.String(64),nullable=False)
    serves = db.Column(db.String(64),nullable=False)
    price = db.Column(db.Float, nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'))
    
    def __repr__(self):
        str = "Id: {}, Name: {}, Description: {}, Image: {}, Size: {}, Serves: {}, Price: {}, Category: {}\n" 
        str =str.format( self.id, self.name,self.description,self.image, self.size, self.serves, self.price, self.category_id)
        return str

class Order(db.Model):
    __tablename__='orders'
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.Boolean, default=False)
    firstname = db.Column(db.String(64))
    lastname = db.Column(db.String(64))
    email = db.Column(db.String(128))
    phone = db.Column(db.String(32))
    deliverydate = db.Column(db.DateTime)
    deliveryaddress = db.Column(db.String(128))
    totalprice = db.Column(db.Float)
    date = db.Column(db.DateTime)
    cakes = db.relationship("Cake", secondary=orderdetails, backref="orders")
    
    def __repr__(self):
        str = "id: {}, Status: {}, Firstname: {}, Lastname: {}, Email: {}, Phone: {}, Delivery Date: {}, Delivery Address: {}, Date: {}, Cakes: {}, Total Price: {}\n" 
        str =str.format( self.id, self.status,self.firstname,self.lastname, self.email, self.phone, self.deliverydate, self.deliveryaddress, self.date, self.cakes, self.totalprice)
        return str

miascakehouse/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, StringField,DateField
from wtforms.validators import InputRequired, email

# Create Checkout Form
class CheckoutForm(FlaskForm):
    firstname = StringField("First name", validators=[InputRequired()])
    lastname = StringField("Last name", validators=[InputRequired()])
    email = StringField("Email", validators=[InputRequired(), email()])
    phone = StringField("Phone number", validators=[InputRequired()])
    deliverydate = DateField("Delivery date",validators=[InputRequired()])
    deliveryaddress = StringField("Delivery address",validators=[InputRequired()])
    submit = SubmitField("SUBMIT ORDER")

# Create Search Form
class SearchForm(FlaskForm):
    searched = StringField("Searched",validators=[InputRequired()])
    submit = SubmitField("Search")

miascakehouse/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

db=SQLAlchemy()
app=Flask(__name__)

def create_app():
    app.debug=True
    app.secret_key='Mi4sC4k3H0us3!*'
    
    app.config['SQLALCHEMY_DATABASE_URI']='sqlite:///miascakehouse.sqlite' #create database with SQLite
    
    db.init_app(app)

    bootstrap = Bootstrap(app)
    
    from . import views
    app.register_blueprint(views.bp)
    from . import admin #after the data is loaded, this line can be commented out
    app.register_blueprint(admin.bp) #after the data is loaded, this line can be commented out
   
    return app

@app.errorhandler(404) 
def not_found(e): 
  return render_template("404.html")

@app.errorhandler(500)
def internal_error(e):
  return render_template("500.html")

miascakehouse/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import Category, Cake, Order
from datetime import datetime
from .forms import CheckoutForm, SearchForm
from . import db

bp = Blueprint('main', __name__)

# Create homepage
@bp.route('/')
def index():
    categories = Category.query.order_by(Category.name).all()
    return render_template('index.html', categories=categories)

# Create cake details page
@bp.route('/cakes/<int:categoryid>/')
def categorycakes(categoryid):
    cakes = Cake.query.filter(Cake.category_id == categoryid)
    return render_template('categorycakes.html', cakes=cakes)

# Create Shopping Cart function
@bp.route('/order', methods=['POST', 'GET'])
def order():
    cake_id = request.values.get('cake_id')

    if 'order_id' in session.keys():
        order = Order.query.get(session['order_id'])

    else:
        order = None

    if order is None:
        order = Order(status=False, firstname='', lastname='', email='', phone='', totalprice=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('There was an issue creating a new order!')
            order = None

    totalprice = 0
    if order is not None:
        for cake in order.cakes:
            totalprice = totalprice + cake.price

    if cake_id is not None and order is not None:
        cake = Cake.query.get(cake_id)
        if cake not in order.cakes:
            try:
                order.cakes.append(cake)
                db.session.commit()
            except:
                return 'There was an issue adding the cake to your shopping cart!'
            return redirect(url_for('main.order'))
        else:
            flash('This cake has been successfully added to your shopping cart!')
            return redirect(url_for('main.order'))

    return render_template('order.html', order=order, totalprice=totalprice)

# Create Delete cake from the shopping cart function
@bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id = request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        cake_to_delete = Cake.query.get(id)
        try:
            order.cakes.remove(cake_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'There was an issue deleting this cake from your order'
    return redirect(url_for('main.order'))

# Create delete order/empty cart function
@bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All cakes have been successfully deleted from your shopping cart!')
    return redirect(url_for('main.index'))

# Create checkout function
@bp.route('/checkout/', methods=['POST', 'GET'])
def checkout():
    form = CheckoutForm()
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])

        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.lastname = form.lastname.data
            order.email = form.email.data
            order.phone = form.phone.data
            order.deliverydate = form.deliverydate.data
            order.deliveryaddress=form.deliveryaddress.data
            totalprice = 0
            for cake in order.cakes:
                totalprice = totalprice + cake.price
            order.totalprice = totalprice
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash('Thank you! Your order has been received and our team member will contact you shortly!')
                return redirect(url_for('main.index'))
            except:
                return 'There was an issue completing your order!'

    return render_template('checkout.html', form=form)

# Pass search result to NavBar in base
@bp.context_processor
def base():
    form = SearchForm()
    return dict(form=form)

# Create Search function
@bp.route('/search',methods=['POST'])
def search():
    form = SearchForm()
    cakes = Cake.query
    if form.validate_on_submit():
        searched = form.searched.data
        cakes = cakes.filter(Cake.description.like('%'+searched+'%'))
        cakes = cakes.order_by(Cake.name).all()
        return render_template("search.html",form=form, searched = searched, cakes=cakes)
    else:
        return render_template("404.html")

miascakehouse/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" 
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>Mia's Cake House</title>
    </head>

    <body>
        <header>
            <div>
                <!--Using NavBar for the navigation-->
                <nav class="navbar navbar-expand-lg navbar-dark text-white" style="background-color: #A76571;">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class ="navbar-brand" href="#">
                        <img src="{{url_for('static', filename='image/Logo.png')}}" width="50" height="50" alt="Logo">
                    </a>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                      <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                          <a class="nav-link font-weight-bold" href="{{ url_for('main.index') }}">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link font-weight-bold" href="{{url_for('main.categorycakes',categoryid=1)}}">Sponge Cakes</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link font-weight-bold" href="{{url_for('main.categorycakes',categoryid=2)}}">Cheesecakes</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link font-weight-bold" href="{{url_for('main.categorycakes',categoryid=3)}}">Mud Cakes</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link font-weight-bold" href="{{url_for('main.categorycakes',categoryid=4)}}">Special Cakes</a>
                        </li>
                      </ul>

                      <!--Using Button for Account and Shopping Cart-->
                      <div> 
                        <a class="btn btn-warning text-dark my-2 my-sm-0" href="#" role="button" > 
                          <svg id="i-user" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="20" height="20" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                            <path d="M22 11 C22 16 19 20 16 20 13 20 10 16 10 11 10 6 12 3 16 3 20 3 22 6 22 11 Z M4 30 L28 30 C28 21 22 20 16 20 10 20 4 21 4 30 Z" />
                          </svg>
                        </a>
                        <a class="btn btn-warning text-dark my-2 my-sm-0" href="{{url_for('main.order')}}" role="button" > 
                          <svg id="i-cart" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="20" height="20" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                            <path d="M6 6 L30 6 27 19 9 19 M27 23 L10 23 5 2 2 2" />
                            <circle cx="25" cy="27" r="2" />
                            <circle cx="12" cy="27" r="2" />
                          </svg>
                        </a>
                      </div>

                      <!--Using Form for Search function-->
                      <form class="d-flex" method="POST" action="{{url_for('main.search')}}">
                        {{form.hidden_tag()}}
                        <input class="form-control mx-1" type="search" placeholder="Type your search here" aria-label="Search", name="searched">
                        <button class="btn btn-warning" type="submit">Search</button>
                      </form>
                    </div>
                </nav>
            </div>
            
            <!-- Using Alert for flashed messages -->
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="alert alert-warning" role="alert">
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                </div>
            {% endif %}
            {% endwith %} 

            <!--Using Carousel to display banners-->
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="{{url_for('static', filename='image/Banner 1.png')}}" class="d-block w-100" alt="Introduction">
                  </div>
                  <div class="carousel-item">
                    <img src="{{url_for('static', filename='image/Banner 2.png')}}" class="d-block w-100" alt="Seasonal special offer">
                  </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
            </div>
              
        </header>

        <!-- Main part depending on each page content -->
        <div class = container-fluid">
          <main>
            {% block main %}{% endblock %}
          </main>
        </div>

      <!--Footer-->
        <footer class="text-white pt-5 pb-4" style="background-color: #A76571;">
          <div class = "container text-center text-md-left">
            <div class = "row text-center text-md-left">
              <div class = "col-md-3 col-lg-3 col-xl-3 mx-auto mt-3 text-center">
                <img src="{{url_for('static', filename='image/Logo.png')}}" width="192" height="192" alt="Logo">
              </div>
              <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                <h5 class ="text-uppercase mb-4 font-weight-bold text-warning">About Us</h5>
                <p>
                  <a href="#" class="text-white">Our Value</a>
                </p>
                <p>
                  <a href="#" class="text-white">Testimonials</a>
                </p>
                <p>
                  <a href="#" class="text-white">Offers</a>
                </p>
                <p>
                  <a href="#" class="text-white">FAQ</a>
                </p>
              </div>
              <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold text-warning">Categories</h5>
                <p>
                  <a href="{{url_for('main.categorycakes',categoryid=1)}}" class="text-white">Sponge Cakes</a>
                </p>
                <p>
                  <a href="{{url_for('main.categorycakes',categoryid=2)}}" class="text-white">Cheesecakes</a>
                </p>
                <p>
                  <a href="{{url_for('main.categorycakes',categoryid=3)}}" class="text-white">Mud Cakes</a>
                </p>
                <p>
                  <a href="{{url_for('main.categorycakes',categoryid=4)}}" class="text-white">Special Cakes</a>
                </p>
              </div>
              <div class = "col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold text-warning"> Contact</h5>
                <p>
                  <svg id="i-location" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                    <circle cx="16" cy="11" r="4" />
                    <path d="M24 15 C21 22 16 30 16 30 16 30 11 22 8 15 5 8 10 2 16 2 22 2 27 8 24 15 Z" />
                  </svg> 5 Spot St, Kedron, QLD 4031
                </p>
                <p>
                  <svg id="i-mail" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                    <path d="M2 26 L30 26 30 6 2 6 Z M2 6 L16 16 30 6" />
                </svg> miascakehouse@gmail.com
                </p>
                <p>
                  <svg id="i-telephone" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                    <path d="M3 12 C3 5 10 5 16 5 22 5 29 5 29 12 29 20 22 11 22 11 L10 11 C10 11 3 20 3 12 Z M11 14 C11 14 6 19 6 28 L26 28 C26 19 21 14 21 14 L11 14 Z" />
                    <circle cx="16" cy="21" r="4" />
                </svg> +61 432 666 888
                </p>
                
              </div>
            </div>
              <hr class = "mb-4">
                <p class="text-center"> Copyright &copy;2022. All rights reserved by:
                  <a>
                    <strong class="text-warning">Mia's Cake House</strong>
                  </a>
                </p>
              </hr>
          </div>
        </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    </body>
</html>

miascakehouse/templates/categorycakes.html
{% extends 'base.html' %}

{% block main %}
<!-- Display all cakes in each category -->
<section>
<div class="container">
    <div class="row mt-5 mb-3">
        <div class = "col-md-6 offset-md-3 text-center">
            <div class="font-weight-bold" style="color:rgb(135, 70, 43)">
                <h2><strong>EXPLORE OUR BEAUTIFUL CAKES</strong></h2>
            </div>
        </div>
    </div>       
    <div class="card-deck">
        {% for cake in cakes%}
        <!-- Display cake details including image, description, size, serves, price -->
        <div class="card mx-2 my-5">
            <img class="card-img-top" src="{{url_for('static', filename='image/'+cake.image)}}" alt="Cake image">
            <div class="card-body">
                <h4 class="card-title" style="color:rgb(135, 70, 43)">{{cake.name}}</h4>
                <p class="card-text" style="color:rgb(135, 70, 43)">{{cake.description}}</p>
                <h6 class="card-text" style="color:rgb(135, 70, 43)">Size: {{cake.size}}</h6>
                <h6 class="card-text" style="color:rgb(135, 70, 43)">Serves: {{cake.serves}}</h6>
                <h6 class="card-text" style="color:rgb(135, 70, 43)">Price: {{"$%.2f"|format(cake.price)}}</h6>
            </div>

            <!-- Display Add to Cart function -->
            <div class="card-footer">
                <form action="{{ url_for('main.order') }}">
                    <input type="hidden" id="cake_id" name="cake_id" value="{{ cake.id }}">
                    <input class="btn btn-warning" style="color:rgb(135, 70, 43)" type="submit" value="Add to Cart">
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</section>
{% endblock %}

miascakehouse/templates/checkout.html
rr{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block main %}
<!-- Display Checkout Form -->
<section>
    <div class="container">
        <div class="row mt-5 mb-3">
            <div class = "col-md-6 offset-md-3 text-center">
                <div class="font-weight-bold" style="color:rgb(135, 70, 43)">
                    <h2><strong> CHECKOUT</strong></h2>
                </div>
                <p style="color:rgb(135, 70, 43)">
                    Please provide your details below to complete your order. Thank you!
                </p>
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class = "col-md-6 offset-md-3">
                <form class="form form-horizontal" method="post" role="form">
                    {{ form.hidden_tag() }}
                    {{ wtf.form_errors(form, hiddens="only") }}
                    <div style="color:rgb(135, 70, 43)"">
                        {{ wtf.form_field(form.firstname) }}
                        {{ wtf.form_field(form.lastname) }}
                        {{ wtf.form_field(form.email) }}
                        {{ wtf.form_field(form.phone) }}
                        {{ wtf.form_field(form.deliverydate) }}
                        {{ wtf.form_field(form.deliveryaddress) }}
                    </div>
                    <button type="submit" class="btn btn-warning">
                        {{ wtf.form_field(form.submit) }}
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

miascakehouse/templates/index.html
{% extends 'base.html' %}

{% block main %}
<!-- Display brief About us introduction about the shop -->
<div class="jumbotron jumbotron-fluid text-white" style="background-color:#C38D94">
    <div class="container" >
        <h1 class="text-center" >ABOUT US</h1>
        <h5 class="font-italic" > "...Mia's Cake House was open in 2019. We are a local cake shop based in Brisbane and we pride ourselves
          in making delicious and beautiful cakes both pre-made or custom-made to best suit your special occasions. Browse our categories of cake below to find yourself
          a wonderful cake and rest assured that you will enjoy it to the very last bit..."
        </h5>
    </div>
</div>

<!-- Display all categories of cake available -->
<main>  
<div class="container">
    <div class="row mt-5 mb-3">
        <div class = "col-md-6 offset-md-3 text-center">
            <div class="font-weight-bold" style="color:rgb(135, 70, 43)">
                <h2><strong>EXPLORE OUR MAIN CATEGORIES</strong></h2>
            </div>
        </div>
    </div>       
    <div class="card-deck mx-5 my-5">
        {% for category in categories %}
        <div class="card">
            <img class="card-img-top" src="{{url_for('static', filename='image/'+category.image)}}" alt="Card image">
            <div class="card-body">
                <h4 class="card-title font-weight-bold" style="color:rgb(135, 70, 43)">{{category.name}}</h4>
                <p class="card-text" style="color:rgb(135, 70, 43)">{{category.description}}</p>
            </div>
            <div class="card-footer"><a href= "{{ url_for('main.categorycakes', categoryid=category.id) }}" class="btn btn-warning" style="color:rgb(135, 70, 43)">View cakes</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>    
</main>
{% endblock %} 

miascakehouse/templates/order.html
{% extends 'base.html' %}

{% block main %}
<!-- Display details of Shopping Cart -->
<section>  
    <div class="container">
        <div class="row mt-5 mb-3">
            <div class = "col-md-6 offset-md-3">
                <div class="text-center" style="color:rgb(135, 70, 43)">
                    <h2 class="font-weight-bold"> SHOPPING CART</h2>
                </div>
            </div>
        </div>
       
        {% for cake in order.cakes %}
        <div class="row shadow-md my-row mb-3">

                <!-- Display cake details include cake name, image, description, size, serves -->
                <div class="col-md-6 offset-md-3">
                    <h5 class="card-header" style="color:rgb(135, 70, 43)" >{{cake.name}}</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-4">
                                <img class="img-thumbnail" src="{{url_for('static', filename=('image/' + cake.image))}}">
                            </div>
                            <div class="col-8">
                                <p class="card-text" style="color:rgb(135, 70, 43)"> {{cake.description}}</p>   
                                <h6 class="card-text" style="color:rgb(135, 70, 43)">Size: {{cake.size}} </h6>
                                <h6 class="card-text" style="color:rgb(135, 70, 43)">Serves: {{cake.serves}} </h6>
                            </div>  
                        </div>                      
                    </div>
                </div>
                <br></br>

                <!-- Display Price and Delete button -->
                <div class="col-sm-3">
                        <h5 style="color:rgb(135, 70, 43)">{{ "$%.2f"|format(cake.price) }}</h5>
                        <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                            <input type="hidden" id="id" name="id" value="{{cake.id}}">
                            <input type="submit" value="Delete" class="btn btn-warning mb-3" style="color:rgb(135, 70, 43)">
                        </form> 
                </div>
        </div>
        {% endfor %}
        
        <!-- Display Total Price and page controls -->
        <section>
            <div class="col-md-6 offset-md-3 mt-3 mb-3">
                <h5 class="mt-4" style="color:rgb(135, 70, 43)">Total price = {{ "$%.2f"|format(totalprice) }}</h5>
            </div>
        
            <div class="rcol-md-6 offset-md-3 mt-3 mb-5">
                <a href="{{ url_for('main.index', _anchor='categories_anchor') }}" class="btn btn-warning mr-4" style="color:rgb(135, 70, 43)">Continue shopping</a>
                
                <!-- Only display Checkout and Empty Cart button if cart is NOT empty -->
                {% if order.cakes %}
                <a href="{{ url_for('main.checkout') }}" class="btn btn-warning mr-4" style="color:rgb(135, 70, 43)">Checkout</a>
                <a href="{{ url_for('main.deleteorder') }}" class="btn btn-warning" style="color:rgb(135, 70, 43)">Empty Cart</a>
                {% endif %}
            </div>
        </section>
    </div>
</section>
{% endblock %}

miascakehouse/templates/search.html
{% extends 'base.html' %}

{% block main %}
<section>  
    <div class="container">
        <div class="col-md-6 offset-md-3 mt-3 mb-3mt-4 mb-4" style="color:rgb(135, 70, 43)">
            <h2>Search result(s) for: <em>{{searched}}</em></h2>
        </div>
    
        <!-- Display search results -->
        {% if cakes %}
        
        {%for cake in cakes%}
        <div class="row mt-3 mb-3">

            <!-- Display search results with cake name (with link to cake details page), description, size, serves -->
            <div class="col-sm-10 card">
                <a href= "{{ url_for('main.categorycakes', categoryid=cake.category_id) }}" class="card-header" style="color:rgb(135, 70, 43)" ><strong>{{cake.name}}</strong></a>
                <div class="card-body">
                    <div class="row">
                        <div class="col-2">
                            <img class="img-thumbnail" src="{{url_for('static', filename=('image/' + cake.image))}}">
                        </div>
                        <div class="col-10">
                            <p class="card-text" style="color:rgb(135, 70, 43)"> {{cake.description}}</p>  
                            <p class="card-text" style="color:rgb(135, 70, 43)">Size: {{cake.size}}</p>
                            <p class="card-text" style="color:rgb(135, 70, 43)">Serves: {{cake.serves}}</p> 
                        </div>  
                    </div>                      
                </div>
            </div>
            <br></br>

            <!-- Display Price and Add to Cart button -->
            <div class="col-sm-2">
                    <h5 style="color:rgb(135, 70, 43)">{{"$%.2f"|format(cake.price)}}</h5>
                    <form action="{{ url_for('main.order') }}">
                        <input type="hidden" id="cake_id" name="cake_id" value="{{ cake.id }}">
                        <input class="btn btn-warning" style="color:rgb(135, 70, 43)" type="submit" value="Add to Cart">
                    </form>
            </div>
        </div>
        
        {% endfor %}

        {% else %}
        <div class="col-md-6 offset-md-3 mt-3 mb-3 mt-4 mb-4">   
            <h5 style="color:rgb(135, 70, 43)">Sorry, <strong>{{searched}}</strong> was not found!</h5>
        </div>
        {% endif %}
    </div>  
</section>
{% endblock %}